/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitnesstracker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

import javax.swing.table.DefaultTableModel;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import java.util.List;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ashle
 */
public class MainScreenExerciseFood extends javax.swing.JFrame {

    public static class Food {
        private int food_id;
        private String food_name;
        private int calories;

        // Constructor, getters, setters
        public Food(int food_id, String food_name, int calories) {
            this.food_id = food_id;
            this.food_name = food_name;
            this.calories = calories;
        }

        // Getters
        public int getFoodId() { return food_id; }
        public String getFoodName() { return food_name; }
        public int getCalories() { return calories; }
    }
    
    int loggedInUserID;
    String units = "Miles";
    List<Food> foodList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreenExerciseFood.class.getName());

    /**
     * Creates new form MainScreen
     */
    public MainScreenExerciseFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        SignupPanel = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        createAccountButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        MainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersDisplay = new javax.swing.JTextArea();
        getUserButton = new javax.swing.JButton();
        getUserButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ExerciseFoodEntry = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        refreshExerciseButton = new javax.swing.JButton();
        refreshDietButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        dietTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ExerciseType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AddExerciseButton = new javax.swing.JButton();
        DistanceSpinner = new javax.swing.JSpinner();
        StartTimeSpinner = new javax.swing.JSpinner();
        EndTimeSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        foodNameCombo = new javax.swing.JComboBox<>();
        foodCalories = new javax.swing.JSpinner();
        dietDateTime = new javax.swing.JSpinner();
        AddDietButton = new javax.swing.JButton();

        jLabel13.setText("End Time");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(187, 239, 206));

        jPanel1.setBackground(new java.awt.Color(187, 239, 206));
        jPanel1.setLayout(new java.awt.CardLayout());

        jTextField2.setText("Username");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        signupButton.setText("Sign Up");
        signupButton.addActionListener(this::signupButtonActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setText("Fitness Tracker");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signupButton))
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupButton)
                    .addComponent(loginButton))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.add(LoginPanel, "LoginPanel");

        jTextField3.setText("Username");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(this::createAccountButtonActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setText("Fitness Tracker");

        jPasswordField2.setText("jPasswordField1");

        jTextField4.setText("Email");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        javax.swing.GroupLayout SignupPanelLayout = new javax.swing.GroupLayout(SignupPanel);
        SignupPanel.setLayout(SignupPanelLayout);
        SignupPanelLayout.setHorizontalGroup(
            SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanelLayout.createSequentialGroup()
                .addGroup(SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7))
                    .addGroup(SignupPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccountButton)
                            .addGroup(SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4)))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        SignupPanelLayout.setVerticalGroup(
            SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccountButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.add(SignupPanel, "SignupPanel");

        jLabel3.setText("Goals/Charts");

        jLabel4.setText("Share With Friends");

        jLabel5.setText("Find Friends");

        jTextField1.setText("Enter a username");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        usersDisplay.setColumns(20);
        usersDisplay.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        usersDisplay.setRows(5);
        jScrollPane1.setViewportView(usersDisplay);

        getUserButton.setText("Get all users");
        getUserButton.addActionListener(this::getUserButtonActionPerformed);

        getUserButton2.setText("Get all users");
        getUserButton2.addActionListener(this::getUserButton2ActionPerformed);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(userTable);

        jButton1.setText("View Exercises and Food");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(getUserButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18))))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(logoutButton))
                        .addGap(0, 250, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(getUserButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getUserButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton))
                    .addComponent(getUserButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(MainPanel, "MainPanel");

        ExerciseFoodEntry.setBackground(new java.awt.Color(187, 239, 206));

        jLabel8.setText("Your Exercise History");

        jLabel9.setText("Your Diet History");

        refreshExerciseButton.setText("Refresh");
        refreshExerciseButton.addActionListener(this::refreshExerciseButtonActionPerformed);

        refreshDietButton.setText("Refresh");
        refreshDietButton.addActionListener(this::refreshDietButtonActionPerformed);

        exerciseTable.setAutoCreateRowSorter(true);
        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Exercise ID", "Type", "Distance", "Start Time", "End Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exerciseTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(exerciseTable);

        jScrollPane6.setViewportView(jScrollPane3);

        dietTable.setAutoCreateRowSorter(true);
        dietTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Food Name", "Calories", "Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dietTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dietTable.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(dietTable);
        dietTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane5.setViewportView(jScrollPane4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Add an Exercise");

        ExerciseType.setEditable(true);
        ExerciseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Running", "Walking", "Cycling", "Swimming", "Weights" }));
        ExerciseType.addActionListener(this::ExerciseTypeActionPerformed);

        jLabel2.setText("Type");

        jLabel10.setText("Distance");

        jLabel11.setText("Start Time");

        jLabel12.setText("End Time");

        AddExerciseButton.setText("Add Exercise");
        AddExerciseButton.addActionListener(this::AddExerciseButtonActionPerformed);

        DistanceSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(200.0f), Float.valueOf(0.1f)));

        StartTimeSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        EndTimeSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        jLabel14.setText("Miles");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Add a Diet Entry");

        jLabel16.setText("Food Name");

        jLabel17.setText("Calories");

        jLabel18.setText("Date/Time");

        foodNameCombo.setEditable(true);
        foodNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        foodNameCombo.addActionListener(this::foodNameComboActionPerformed);

        foodCalories.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3000, 10));

        dietDateTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        AddDietButton.setText("Add Diet Entry");
        AddDietButton.addActionListener(this::AddDietButtonActionPerformed);

        javax.swing.GroupLayout ExerciseFoodEntryLayout = new javax.swing.GroupLayout(ExerciseFoodEntry);
        ExerciseFoodEntry.setLayout(ExerciseFoodEntryLayout);
        ExerciseFoodEntryLayout.setHorizontalGroup(
            ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshExerciseButton)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ExerciseFoodEntryLayout.createSequentialGroup()
                            .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                                    .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExerciseFoodEntryLayout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)))
                            .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                                    .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ExerciseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EndTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(StartTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddExerciseButton))
                                .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                                    .addComponent(DistanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshDietButton))
                    .addComponent(jLabel15)
                    .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                        .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(41, 41, 41)
                        .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                                .addComponent(foodNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(AddDietButton))
                            .addComponent(dietDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ExerciseFoodEntryLayout.setVerticalGroup(
            ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExerciseFoodEntryLayout.createSequentialGroup()
                        .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(refreshDietButton)
                            .addComponent(jLabel8)
                            .addComponent(refreshExerciseButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExerciseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(AddExerciseButton)
                    .addComponent(jLabel16)
                    .addComponent(foodNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDietButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DistanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(foodCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(StartTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(dietDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExerciseFoodEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EndTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(ExerciseFoodEntry, "ExerciseFoodEntry");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        CardLayout card = (CardLayout)jPanel1.getLayout();
        card.show(jPanel1, "SignupPanel");
    }//GEN-LAST:event_signupButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        CardLayout card = (CardLayout)jPanel1.getLayout();
        card.show(jPanel1, "LoginPanel");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        CardLayout card = (CardLayout)jPanel1.getLayout();
        loggedInUserID = 1;
        card.show(jPanel1, "MainPanel");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        CardLayout card = (CardLayout)jPanel1.getLayout();
        JOptionPane.showMessageDialog(jPanel1, "Account not created because this isn't implemented yet");
        card.show(jPanel1, "LoginPanel"); 
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void getUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUserButtonActionPerformed
        try {
        // 1. Call the API class
        APIclient api = new APIclient();
        String result = api.getAllUsers();

        // 2. Convert to Pretty JSON
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        JsonElement jsonElement = JsonParser.parseString(result);
        String prettyResult = gson.toJson(jsonElement);
        
        // 3. Display the result
        usersDisplay.setText(prettyResult);

    } catch (Exception e) {
        usersDisplay.setText("Failed: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_getUserButtonActionPerformed

    private void getUserButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUserButton2ActionPerformed
        try {
        // 1. Fetch the data
        APIclient api = new APIclient();
        String jsonResponse = api.getAllUsers();

        // 2. Define the Columns
        String[] columnNames = {"ID", "Username", "First Name", "Last Name", "Email", "Start Date"};
        
        // 3. Create a Table Model
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // 4. Parse the JSON Object with "data" array
        JsonObject root = JsonParser.parseString(jsonResponse).getAsJsonObject();
        JsonArray dataList = root.getAsJsonArray("data");

        // 5. Loop through the array and add rows
        for (JsonElement element : dataList) {
            JsonObject user = element.getAsJsonObject();

            Object[] row = {
                user.get("user_id").getAsInt(),
                user.get("username").getAsString(),
                user.get("first_name").getAsString(),
                user.get("last_name").getAsString(),
                user.get("email").getAsString(),
                user.get("start_date").getAsString()
            };

            model.addRow(row);
        }

        // 6. Apply the model to your JTable
        userTable.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_getUserButton2ActionPerformed

    private void refreshExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshExerciseButtonActionPerformed
        try {
        // 1. Fetch the data
        APIclient api = new APIclient();
        String jsonResponse = api.getExercisesByUser(loggedInUserID); 
        System.out.println("Exercise response:" + jsonResponse);

        // 2. Define Columns
        String[] columnNames = {"Exercise ID", "Type", "Distance", "Start Time", "End Time", "Date"};
        
        // 3. Create Model
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // 4. Parse the JSON Array (direct array response)
        JsonArray dataList = JsonParser.parseString(jsonResponse).getAsJsonArray();

        // 5. Loop through the array and add rows
        for (JsonElement element : dataList) {
            JsonObject exercise = element.getAsJsonObject();

            Object[] row = {
                exercise.get("exercise_id").getAsInt(),
                exercise.get("type").getAsString(),
                exercise.get("distance").getAsDouble(),
                exercise.get("start_time").getAsString(),
                exercise.get("end_time").getAsString(),
                exercise.get("date").getAsString()
            };

            model.addRow(row);
        }

        // 6. Apply the model
        exerciseTable.setModel(model);
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Error loading exercises: " + e.getMessage());
    }
    }//GEN-LAST:event_refreshExerciseButtonActionPerformed

    private void refreshDietButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshDietButtonActionPerformed
    try {
        // Get the diet entries for the user ID
        APIclient api = new APIclient();
        String jsonResponse = api.getDietsByUser(loggedInUserID); 
        System.out.println("Diet response: " + jsonResponse);

        // Prepare table setup
        String[] columnNames = {"Food Name", "Calories", "Time", "Date"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // Parse the jsonResponse
        JsonArray dataList = JsonParser.parseString(jsonResponse).getAsJsonArray();

        // Display each element in the diet array nicely
        for (JsonElement element : dataList) {
            JsonObject diet = element.getAsJsonObject();

            // Get the food name and calories from food ID
            String food_name = "Unknown";
            int calories = 0;
            int foodId = diet.get("food_id").getAsInt();
            String foodResponse = api.getFoodById(foodId); 
            JsonObject foodRoot = JsonParser.parseString(foodResponse).getAsJsonObject();

            if (foodRoot.has("data")) {
                JsonArray foodArray = foodRoot.getAsJsonArray("data");
                JsonObject food = foodArray.get(0).getAsJsonObject();
                food_name = food.get("food_name").getAsString();
                calories = food.get("calories").getAsInt();
            }
            
            // date/time formatting
            SimpleDateFormat isoFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
                    isoFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            Date timeDate = isoFormat.parse(diet.get("time").getAsString());
            Date dateDate = isoFormat.parse(diet.get("date").getAsString());
            
            // create row
            Object[] row = {
                food_name,
                calories,
                timeFormat.format(timeDate),
                dateFormat.format(dateDate)
            };
            
            // add row to table model
            model.addRow(row);
        }
        
        // apply table model
        dietTable.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_refreshDietButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout card = (CardLayout)jPanel1.getLayout();
        card.show(jPanel1, "ExerciseFoodEntry"); 
        
        // functions to prepare screen (will freeze for a second until these complete)
        refreshDietButtonActionPerformed(evt);
        refreshExerciseButtonActionPerformed(evt);
        getListOfFoodCalories();
        populateFoodNames();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExerciseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExerciseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExerciseTypeActionPerformed

    private void AddExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddExerciseButtonActionPerformed
    try {
        // Create a json object to send to the backend
        JsonObject exerciseJson = new JsonObject();

        exerciseJson.addProperty("user_id", loggedInUserID);
        exerciseJson.addProperty("type", ExerciseType.getSelectedItem().toString());
        exerciseJson.addProperty("distance", DistanceSpinner.getValue().toString());
        
        // Getting date and time from date spinners
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        Date start = (Date) StartTimeSpinner.getValue();
        Date end = (Date) EndTimeSpinner.getValue();

        exerciseJson.addProperty("start_time", start != null ? timeFormat.format(start) : "");
        exerciseJson.addProperty("end_time", end != null ? timeFormat.format(end) : "");
        exerciseJson.addProperty("date", start != null ? dateFormat.format(start) : "");
        
        System.out.println(exerciseJson);
        
        String exercise = exerciseJson.toString();
        
        APIclient api = new APIclient();
        api.createExercise(exercise);
        
        // update exercise table
        refreshExerciseButtonActionPerformed(evt);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_AddExerciseButtonActionPerformed

    private void foodNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodNameComboActionPerformed
        // when a food is selected set the calories from the dictionary into the foodCalories
        
        // Get the selected item as String
        String selectedFoodName = (String) foodNameCombo.getSelectedItem();
        
        if (selectedFoodName != null && !selectedFoodName.equals("-- Select Food --")) {
            // Simple loop to find and update
            for (Food food : foodList) {
                if (food.getFoodName().equals(selectedFoodName)) {
                    foodCalories.setValue(food.getCalories());
                    return; // Exit once found
            }
        }
        // If not found (custom entry), add handling here if we have time
        // foodCalories.setValue(0);
    }
    }//GEN-LAST:event_foodNameComboActionPerformed

    private void AddDietButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDietButtonActionPerformed
    try {
        // create api client
        APIclient api = new APIclient();
        
        // Create a json object to send to the backend
        JsonObject dietJson = new JsonObject();

        dietJson.addProperty("user_id", loggedInUserID);
        
        // Get the ID of the food or create a new one
        String selectedFood = foodNameCombo.getSelectedItem().toString();
        int selectedCalories = (Integer) foodCalories.getValue();
        
        int food_id = -1;
        
        // search it in the list
        for (Food food : foodList) {
            if (selectedFood.equalsIgnoreCase(food.food_name) 
                    && selectedCalories == food.calories) {
                food_id = food.food_id;
                break;
            }
        } 
        // if we found a match create entry with food_id
        // otherwise, create a new food entry:
        String response = "";
        if (food_id == -1) {
            JsonObject foodJson = new JsonObject();
            foodJson.addProperty("food_name", selectedFood);
            foodJson.addProperty("calories", selectedCalories);
            
            response = api.createFood(foodJson.toString());
            System.out.println("API response: " + response);
            JsonObject foodResponseJson = JsonParser.parseString(response).getAsJsonObject();
            
            food_id = foodResponseJson.get("food_id").getAsInt();
            
            // update selection lists
            Food newFood = new Food(food_id, selectedFood, selectedCalories);
            foodList.add(newFood);
            
            boolean alreadyInCombo = false;
                for (int i = 0; i < foodNameCombo.getItemCount(); i++) {
                    if (selectedFood.equalsIgnoreCase(foodNameCombo.getItemAt(i))) {
                        alreadyInCombo = true;
                        break;
                    }
                }
                if (!alreadyInCombo) {
                    foodNameCombo.addItem(selectedFood);
                }
                
                System.out.println("Created new food with ID: " + food_id);
        }
        
        
        // Add selected food to diet
        dietJson.addProperty("food_id", food_id);
        
        // Get date and time from spinner
        SimpleDateFormat timeFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        Date foodTime = (Date) dietDateTime.getValue();
        
        dietJson.addProperty("time", foodTime != null ? timeFormat.format(foodTime) : "");
        dietJson.addProperty("date", foodTime != null ? dateFormat.format(foodTime) : "");
        
        System.out.println(dietJson);
        
        String diet = dietJson.toString();    
        api.createDiet(diet);
        
        // update diet table
        refreshDietButtonActionPerformed(evt);

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_AddDietButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreenExerciseFood().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDietButton;
    private javax.swing.JButton AddExerciseButton;
    private javax.swing.JSpinner DistanceSpinner;
    private javax.swing.JSpinner EndTimeSpinner;
    private javax.swing.JPanel ExerciseFoodEntry;
    private javax.swing.JComboBox<String> ExerciseType;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SignupPanel;
    private javax.swing.JSpinner StartTimeSpinner;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JSpinner dietDateTime;
    private javax.swing.JTable dietTable;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JSpinner foodCalories;
    private javax.swing.JComboBox<String> foodNameCombo;
    private javax.swing.JButton getUserButton;
    private javax.swing.JButton getUserButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton refreshDietButton;
    private javax.swing.JButton refreshExerciseButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTable userTable;
    private javax.swing.JTextArea usersDisplay;
    // End of variables declaration//GEN-END:variables

    private void getListOfFoodCalories() {
        Gson gson = new Gson();
        try {
            APIclient api = new APIclient();
            String jsonResponse = api.getAllFoods(); 
            JsonObject jsonObject = gson.fromJson(jsonResponse, JsonObject.class);
            JsonArray dataArray = jsonObject.getAsJsonArray("data");

            // Clear the existing list
            foodList.clear();

            for (JsonElement element : dataArray) {
                JsonObject item = element.getAsJsonObject();

                // Get all three fields from JSON
                int foodId = item.get("food_id").getAsInt();
                String foodName = item.get("food_name").getAsString();
                int calories = item.get("calories").getAsInt();

                // Create Food object and add to list
                Food food = new Food(foodId, foodName, calories);
                foodList.add(food);
            }

            System.out.println(foodList);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void populateFoodNames() {
        
        // Clear and populate combo box
        foodNameCombo.removeAllItems();
        
        // Add a default empty option
        foodNameCombo.addItem("-- Select Food --");
        
        // Add all food items
        for (Food food : foodList) {
            foodNameCombo.addItem(food.food_name);
        }
    }
}
